// AUTO-GENERATED by scratchpad/gen-catalog.js from src/lib/actions.ts — do not edit by hand.
// Metadata only (no imports): the dispatcher looks up the real fn via `import * as actions`.
export interface CatalogParam { name: string; type: string; optional: boolean }
export interface CatalogAction {
  name: string; domain: string; destructive: boolean;
  actorParam: string | null; extraInject: Record<string,string> | null;
  excluded: boolean; params: CatalogParam[];
}
export const ACTION_CATALOG: CatalogAction[] = [
  {
    "name": "updateStudentStatusNote",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "note",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentAdminStatusNote",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "note",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "repairPermissions",
    "domain": "Users",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "triggerWhatsAppNotification",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "type",
        "type": "NotificationType",
        "optional": false
      },
      {
        "name": "variables",
        "type": "Record<string, string>",
        "optional": false
      },
      {
        "name": "recipientPhone",
        "type": "string",
        "optional": true
      }
    ]
  },
  {
    "name": "sendTestWhatsApp",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "templateId",
        "type": "string",
        "optional": false
      },
      {
        "name": "phone",
        "type": "string",
        "optional": false
      },
      {
        "name": "variables",
        "type": "Record<string, string>",
        "optional": false
      }
    ]
  },
  {
    "name": "sendSampleWebhookRequest",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "webhookUrl",
        "type": "string",
        "optional": false
      },
      {
        "name": "mapping",
        "type": "Record<string, string>",
        "optional": false
      }
    ]
  },
  {
    "name": "saveNotificationTemplate",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "data",
        "type": "Omit<NotificationTemplate, 'id' | 'createdAt' | 'updatedAt'>",
        "optional": false
      },
      {
        "name": "id",
        "type": "string",
        "optional": true
      }
    ]
  },
  {
    "name": "createRequestType",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "data",
        "type": "Omit<RequestType, 'id'>",
        "optional": false
      }
    ]
  },
  {
    "name": "updateRequestType",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "id",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "Partial<RequestType>",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteRequestType",
    "domain": "Notifications",
    "destructive": true,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "id",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteUser",
    "domain": "Users",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userIdToDelete",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "changeUserRole",
    "domain": "Users",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "newRole",
        "type": "UserRole",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addApplication",
    "domain": "Applications",
    "destructive": false,
    "actorParam": "employeeId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "universityName",
        "type": "string",
        "optional": false
      },
      {
        "name": "country",
        "type": "string",
        "optional": false
      },
      {
        "name": "major",
        "type": "string",
        "optional": false
      },
      {
        "name": "studentName",
        "type": "string",
        "optional": false
      },
      {
        "name": "employeeId",
        "type": "string | null",
        "optional": false
      }
    ]
  },
  {
    "name": "updateApplicationStatus",
    "domain": "Applications",
    "destructive": false,
    "actorParam": "employeeId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "universityName",
        "type": "string",
        "optional": false
      },
      {
        "name": "major",
        "type": "string",
        "optional": false
      },
      {
        "name": "newStatus",
        "type": "ApplicationStatus",
        "optional": false
      },
      {
        "name": "studentName",
        "type": "string",
        "optional": false
      },
      {
        "name": "employeeId",
        "type": "string | null",
        "optional": false
      },
      {
        "name": "rejectionReason",
        "type": "string",
        "optional": true
      }
    ]
  },
  {
    "name": "bulkUpdateApplicationStatuses",
    "domain": "Applications",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "updates",
        "type": "{ university: string; major: string; status: ApplicationStatus; rejectionReason?: string }[]",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteApplication",
    "domain": "Applications",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "university",
        "type": "string",
        "optional": false
      },
      {
        "name": "major",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateApplicationMajor",
    "domain": "Applications",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "university",
        "type": "string",
        "optional": false
      },
      {
        "name": "oldMajor",
        "type": "string",
        "optional": false
      },
      {
        "name": "newMajor",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentPipelineStatus",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "status",
        "type": "string",
        "optional": false
      },
      {
        "name": "userName",
        "type": "string",
        "optional": false
      },
      {
        "name": "studentName",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "createStudentTask",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "requestTypeId",
        "type": "string",
        "optional": false
      },
      {
        "name": "description",
        "type": "string",
        "optional": false
      },
      {
        "name": "dynamicData",
        "type": "any",
        "optional": true
      }
    ]
  },
  {
    "name": "markTaskAsSeen",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userName",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "markMultipleTasksAsSeen",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskIds",
        "type": "string[]",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userName",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "sendTaskNotification",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": "fromId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskId",
        "type": "string",
        "optional": false
      },
      {
        "name": "fromId",
        "type": "string",
        "optional": false
      },
      {
        "name": "fromName",
        "type": "string",
        "optional": false
      },
      {
        "name": "message",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "sendTask",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "recipientId",
        "type": "string",
        "optional": false
      },
      {
        "name": "content",
        "type": "string",
        "optional": false
      },
      {
        "name": "category",
        "type": "'update' | 'system'",
        "optional": true
      }
    ]
  },
  {
    "name": "addReplyToTask",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskId",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "content",
        "type": "string",
        "optional": false
      },
      {
        "name": "taskAuthorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateTaskStatus",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": "updaterId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskId",
        "type": "string",
        "optional": false
      },
      {
        "name": "status",
        "type": "TaskStatus",
        "optional": false
      },
      {
        "name": "updaterId",
        "type": "string",
        "optional": false
      },
      {
        "name": "reason",
        "type": "string",
        "optional": true
      }
    ]
  },
  {
    "name": "toggleTaskPriority",
    "domain": "Tasks",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskId",
        "type": "string",
        "optional": false
      },
      {
        "name": "isPrioritized",
        "type": "boolean",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteTask",
    "domain": "Tasks",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "taskId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "createNewUser",
    "domain": "Users",
    "destructive": true,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userData",
        "type": "{ name: string; email: string; password: string; civilId: string; phone: string; role: 'admin' | 'employee' | 'department'; department?: string; }",
        "optional": false
      }
    ]
  },
  {
    "name": "createStudent",
    "domain": "Students",
    "destructive": false,
    "actorParam": "creatingUserId",
    "extraInject": {
      "creatingUserRole": "@role",
      "creatingUserCivilId": "@civilId"
    },
    "excluded": false,
    "params": [
      {
        "name": "values",
        "type": "{ studentName: string; studentEmail?: string; phone: string; phone2?: string; phone3?: string; gender?: 'M' | 'F'; internalNumber?: string; highSchoolGrade?: string; targetCountries: string[]; otherCountry?: string; notes?: string; }",
        "optional": false
      },
      {
        "name": "creatingUserId",
        "type": "string",
        "optional": false
      },
      {
        "name": "creatingUserRole",
        "type": "UserRole",
        "optional": false
      },
      {
        "name": "creatingUserCivilId",
        "type": "string | null",
        "optional": true
      },
      {
        "name": "assignedEmployeeId",
        "type": "string | null",
        "optional": true
      }
    ]
  },
  {
    "name": "resolveDuplicate",
    "domain": "Students",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "transferStudent",
    "domain": "Students",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "newEmployee",
        "type": "User",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "studentName",
        "type": "string",
        "optional": false
      },
      {
        "name": "fromEmployeeName",
        "type": "string | null",
        "optional": false
      }
    ]
  },
  {
    "name": "unassignStudent",
    "domain": "Students",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "requestTransfer",
    "domain": "Other",
    "destructive": false,
    "actorParam": "requestingEmployeeId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "reason",
        "type": "string",
        "optional": false
      },
      {
        "name": "requestingEmployeeId",
        "type": "string",
        "optional": false
      },
      {
        "name": "studentName",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "requestStudentDeletion",
    "domain": "Students",
    "destructive": false,
    "actorParam": "employeeId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "employeeId",
        "type": "string",
        "optional": false
      },
      {
        "name": "reason",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addEmployeeNote",
    "domain": "Other",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "content",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addAdminNote",
    "domain": "Other",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "content",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addMissingItemToStudent",
    "domain": "Students",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "itemText",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "removeMissingItemFromStudent",
    "domain": "Students",
    "destructive": true,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "item",
        "type": "string | MissingItem",
        "optional": false
      }
    ]
  },
  {
    "name": "markMissingItemAsReceived",
    "domain": "Students",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "item",
        "type": "string | MissingItem",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addTodo",
    "domain": "Reminders",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "content",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "toggleTodo",
    "domain": "Reminders",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "todoId",
        "type": "string",
        "optional": false
      },
      {
        "name": "completed",
        "type": "boolean",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteTodo",
    "domain": "Reminders",
    "destructive": true,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "todoId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateChecklistItem",
    "domain": "Checklist",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "itemKey",
        "type": "string",
        "optional": false
      },
      {
        "name": "value",
        "type": "boolean",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "getChecklistConfig",
    "domain": "Checklist",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "saveChecklistConfig",
    "domain": "Checklist",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "items",
        "type": "ChecklistConfigItem[]",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "getAdminChecklistConfig",
    "domain": "Checklist",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "saveAdminChecklistConfig",
    "domain": "Checklist",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "items",
        "type": "ChecklistConfigItem[]",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateAdminChecklistItem",
    "domain": "Checklist",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "itemKey",
        "type": "string",
        "optional": false
      },
      {
        "name": "value",
        "type": "boolean",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "setStudentFinalChoice",
    "domain": "Students",
    "destructive": true,
    "actorParam": "updaterId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "university",
        "type": "string",
        "optional": false
      },
      {
        "name": "major",
        "type": "string",
        "optional": false
      },
      {
        "name": "updaterId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "unfinalizeStudentDecision",
    "domain": "Students",
    "destructive": true,
    "actorParam": "updaterId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "updaterId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "markFinalizedAsViewed",
    "domain": "Students",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentIds",
        "type": "string[]",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "clearStudentFlagsForEveryone",
    "domain": "Students",
    "destructive": true,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteStudent",
    "domain": "Students",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "bulkDeleteStudents",
    "domain": "Students",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentIds",
        "type": "string[]",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteStudentDocument",
    "domain": "Students",
    "destructive": true,
    "actorParam": "deleterId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "documentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "documentUrl",
        "type": "string",
        "optional": false
      },
      {
        "name": "deleterId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "markDocumentViewed",
    "domain": "Documents",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "docId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentDocumentNote",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "documentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "note",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "handleEmployeeLogin",
    "domain": "Documents",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "handleEmployeeLogout",
    "domain": "Reports",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "keepAlive",
    "domain": "Reports",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "closeInactiveSessions",
    "domain": "Reports",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "closeForceInactivitySessions",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "updateUserAvatar",
    "domain": "Users",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "avatarUrl",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "getReportStats",
    "domain": "Reports",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "dateRange",
        "type": "{ from: string; to: string; }",
        "optional": false
      }
    ]
  },
  {
    "name": "getEmployeeStudentStats",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "updateStudentIELTS",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "overallScore",
        "type": "number",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentGrade",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "grade",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentStudyLevel",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "level",
        "type": "'Foundation' | 'First Year' | 'Transfer Student'",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "createStudentLogin",
    "domain": "Students",
    "destructive": false,
    "actorParam": "createdByUserId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "description",
        "type": "string",
        "optional": false
      },
      {
        "name": "username",
        "type": "string",
        "optional": false
      },
      {
        "name": "password",
        "type": "string",
        "optional": false
      },
      {
        "name": "notes",
        "type": "string | undefined",
        "optional": false
      },
      {
        "name": "createdByUserId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteStudentLogin",
    "domain": "Students",
    "destructive": true,
    "actorParam": "deletedByUserId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "idToDelete",
        "type": "string",
        "optional": false
      },
      {
        "name": "deletedByUserId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentTargetCountries",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "countries",
        "type": "string[]",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentAcademicIntake",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "semester",
        "type": "string",
        "optional": false
      },
      {
        "name": "year",
        "type": "number",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "seedAcademicTerms",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addAcademicTerm",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "name",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteAcademicTerm",
    "domain": "Students",
    "destructive": true,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "termId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateStudentTerm",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "term",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "sendChatMessage",
    "domain": "Chat",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "content",
        "type": "string",
        "optional": false
      },
      {
        "name": "recipientIds",
        "type": "string[]",
        "optional": true
      },
      {
        "name": "documentPayload",
        "type": "{ name: string; url: string }",
        "optional": true
      }
    ]
  },
  {
    "name": "deleteChatMessage",
    "domain": "Chat",
    "destructive": true,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "messageId",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "triggerDocumentUploadNotification",
    "domain": "Notifications",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "documentName",
        "type": "string",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "notifyStudentUpload",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "token",
        "type": "string",
        "optional": false
      },
      {
        "name": "fileName",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "toggleChangeAgentStatus",
    "domain": "Other",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "status",
        "type": "boolean",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "universities",
        "type": "string[]",
        "optional": true
      }
    ]
  },
  {
    "name": "submitInactivityReport",
    "domain": "Students",
    "destructive": false,
    "actorParam": "employeeId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "employeeId",
        "type": "string",
        "optional": false
      },
      {
        "name": "reportContent",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "processInactivityReminders",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "forceInactivity",
    "domain": "Students",
    "destructive": true,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteUniversity",
    "domain": "Universities",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "id",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "bulkTransferStudents",
    "domain": "Students",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "fromEmployeeId",
        "type": "string",
        "optional": false
      },
      {
        "name": "toEmployeeId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "addEvent",
    "domain": "Reminders",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      },
      {
        "name": "title",
        "type": "string",
        "optional": false
      },
      {
        "name": "description",
        "type": "string",
        "optional": false
      },
      {
        "name": "date",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteEvent",
    "domain": "Reminders",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "eventId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "getMissingItemTemplates",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "saveMissingItemTemplates",
    "domain": "Students",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "items",
        "type": "{ id: string; text: string }[]",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "getFullSystemBackup",
    "domain": "Reports",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "createInvoice",
    "domain": "Invoices",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "any",
        "optional": false
      }
    ]
  },
  {
    "name": "updateInvoice",
    "domain": "Invoices",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "invoiceId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "any",
        "optional": false
      }
    ]
  },
  {
    "name": "updateInvoiceStatus",
    "domain": "Invoices",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "invoiceId",
        "type": "string",
        "optional": false
      },
      {
        "name": "status",
        "type": "InvoiceStatus",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "deleteInvoice",
    "domain": "Invoices",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "invoiceId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "saveInvoiceTemplate",
    "domain": "Invoices",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "any",
        "optional": false
      },
      {
        "name": "id",
        "type": "string",
        "optional": true
      }
    ]
  },
  {
    "name": "deleteInvoiceTemplate",
    "domain": "Invoices",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "templateId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "saveInvoiceSavedItem",
    "domain": "Invoices",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "any",
        "optional": false
      },
      {
        "name": "id",
        "type": "string",
        "optional": true
      }
    ]
  },
  {
    "name": "deleteInvoiceSavedItem",
    "domain": "Invoices",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "itemId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "updateResourceLink",
    "domain": "Documents",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "linkId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "Partial<ResourceLink>",
        "optional": false
      }
    ]
  },
  {
    "name": "updateSharedDocument",
    "domain": "Documents",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "docId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "Partial<SharedDocument>",
        "optional": false
      }
    ]
  },
  {
    "name": "bulkAssignStudents",
    "domain": "Students",
    "destructive": true,
    "actorParam": "requesterId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentIds",
        "type": "string[]",
        "optional": false
      },
      {
        "name": "targetCivilId",
        "type": "string",
        "optional": false
      },
      {
        "name": "requesterId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "rejectStudentDeletion",
    "domain": "Students",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      },
      {
        "name": "reason",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "processStudentReminders",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "params",
        "type": "{\n  userId: string;\n  userRole: string;\n  userDepartment?: string;\n  userCivilId?: string;\n}",
        "optional": false
      }
    ]
  },
  {
    "name": "closeStudentProfile",
    "domain": "Students",
    "destructive": true,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "reason",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "reopenStudentProfile",
    "domain": "Students",
    "destructive": false,
    "actorParam": "adminId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "adminId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "submitJotformApplications",
    "domain": "Applications",
    "destructive": true,
    "actorParam": null,
    "extraInject": null,
    "excluded": true,
    "params": [
      {
        "name": "formData",
        "type": "FormData",
        "optional": false
      }
    ]
  },
  {
    "name": "addCountryApplication",
    "domain": "Applications",
    "destructive": false,
    "actorParam": "userId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "country",
        "type": "string",
        "optional": false
      },
      {
        "name": "major",
        "type": "string",
        "optional": false
      },
      {
        "name": "universities",
        "type": "string",
        "optional": false
      },
      {
        "name": "userId",
        "type": "string",
        "optional": false
      },
      {
        "name": "semesterOverride",
        "type": "string",
        "optional": true
      },
      {
        "name": "guardianDobOverride",
        "type": "string",
        "optional": true
      },
      {
        "name": "applicationEntries",
        "type": "{ university: string; major: string; country: string }[]",
        "optional": true
      }
    ]
  },
  {
    "name": "refreshStudentDuplicateWarning",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "clearStaleDuplicateWarnings",
    "domain": "Students",
    "destructive": false,
    "actorParam": null,
    "extraInject": null,
    "excluded": false,
    "params": []
  },
  {
    "name": "bulkImportStudents",
    "domain": "Students",
    "destructive": false,
    "actorParam": "creatingUserId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "listName",
        "type": "string",
        "optional": false
      },
      {
        "name": "toUpdate",
        "type": "Array<{ studentId: string; acceptedInfo: { country: string; major: string }; importListName?: string; phone2?: string; phone3?: string }>",
        "optional": false
      },
      {
        "name": "toCreate",
        "type": "Array<{ arabicName: string; phone: string; phone2?: string; phone3?: string; gender?: 'M' | 'F'; acceptedInfo: { country: string; major: string }; importListName: string }>",
        "optional": false
      },
      {
        "name": "creatingUserId",
        "type": "string",
        "optional": false
      },
      {
        "name": "listEntries",
        "type": "Array<{ phones: string[]; civilId?: string; country: string; major: string }>",
        "optional": true
      }
    ]
  },
  {
    "name": "updateAcceptedInfo",
    "domain": "Students",
    "destructive": false,
    "actorParam": "authorId",
    "extraInject": null,
    "excluded": false,
    "params": [
      {
        "name": "studentId",
        "type": "string",
        "optional": false
      },
      {
        "name": "data",
        "type": "{ country: string; major: string; importListName?: string } | null",
        "optional": false
      },
      {
        "name": "authorId",
        "type": "string",
        "optional": false
      }
    ]
  }
];
export const ACTION_MAP: Record<string, CatalogAction> = Object.fromEntries(ACTION_CATALOG.map(a => [a.name, a]));
